services:
  auth-service:
    build: ./authentication-service
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=videodb
    depends_on:
      - mysql

  upload-service:
    build: ./upload-video-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=videodb
    volumes:
      - ./videos:/usr/src/app/videos
    depends_on:
      - mysql

  streaming-service:
    build: ./video-streaming-service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=videodb
    volumes:
      - ./videos:/usr/src/app/videos
    depends_on:
      - mysql

  file-system-service:
    build: ./file-system-service
    ports:
      - "3003:3003"
    volumes:
      - ./videos:/usr/src/app/videos
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=videodb
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=videodb
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: